# backend/config/selector_config.py

SELECTOR_PROVIDER = "gemini"

SELECTOR_MODEL = (
    "gemini-2.5-flash-lite"
)

SELECTOR_TIMEOUT = 20

SELECTOR_MAX_RETRIES = 2

SELECTOR_TEMPERATURE = 0.1

SELECTOR_MAX_TOKENS = 1200

SELECTOR_USE_STRUCTURED_OUTPUT = True

SELECTOR_ENABLE_FALLBACK = True

SELECTOR_FALLBACK_SELECTOR = (
    "rule_based"
)

SELECTOR_MIN_CONFIDENCE = 0.65

SELECTOR_ENABLE_REASONING = True

SELECTOR_ENABLE_DETAILED_SCORING = True

SELECTOR_ENABLE_PROVIDER_METADATA = True